#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=00:15:00
# 
# Author: Vasilis Karlaftis

# run the actual python code
singularity exec docker://brainlife/fsl:6.0.4-patched2 main.sh
